Repository syntpump/syntext-py-ua, pull requests merged in 2019-04, with the labels that each got.

#21 Add UDT tag
  pysyntext/libs/arrproc.py
  pysyntext/libs/morphtrain.py
  pysyntext/libs/ud/conllu.py
  pysyntext/libs/ud/mte.py
  pysyntext/libs/ud/udt.py
  pysyntext/libs/ud/udtxposdata.json
  pysyntext/xpostrain.py
Labels: new abstract

#22 Provide autoconfigurations for classes + priority file
  pysyntext/config.json
  pysyntext/configdoc.md
  pysyntext/dominations.json
  pysyntext/predefinator.py
Labels: new abstract

#23 Minor changes set
  pysyntext/anmorphacc.py
  pysyntext/ccmrtrain.py
  pysyntext/config.json
  pysyntext/configdoc.md
  pysyntext/libs/accuracy.py
  pysyntext/libs/ctxmorph.py
  pysyntext/libs/ctxmorphtrain.py
  pysyntext/libs/logs.py
  pysyntext/libs/morphology.py
  pysyntext/libs/tmr/human.py
  pysyntext/libs/tmr/trainbyaffixes.py
  pysyntext/libs/ud/conllu.py
  pysyntext/libs/ud/mte.py
  pysyntext/libs/ud/udt.py
  pysyntext/libs/ud/udtxposdata.json
  pysyntext/predefinator.py
  pysyntext/xpostrain.py
  setup.py
Labels: bug fixing, resctucturing

#24 Fix predefiner
  pysyntext/libs/logs.py
  pysyntext/libs/tmr/human.py
  pysyntext/libs/tmr/trainbyaffixes.py
  pysyntext/predefinator.py
  pysyntext/xpostrain.py
Labels: bug fixing

#27 Fix bugs with relative import and file reading
  pysyntext/config.json
  pysyntext/libs/accuracy.py
  pysyntext/libs/ctxmorphtrain.py
  pysyntext/libs/morphology.py
  pysyntext/libs/tmr/human.py
  pysyntext/libs/tmr/trainbyaffixes.py
  pysyntext/libs/ud/conllu.py
  pysyntext/libs/ud/udt.py
  pysyntext/predefinator.py
  setup.py
Labels: bug fixing

#26 Fix #25: Create UDT from unsorted dictionary
  pysyntext/libs/ud/udt.py
Labels: bug fixing

#28 Update CYK branch to minor
  pysyntext/config.json
  pysyntext/libs/accuracy.py
  pysyntext/libs/ctxmorphtrain.py
  pysyntext/libs/logs.py
  pysyntext/libs/morphology.py
  pysyntext/libs/tmr/human.py
  pysyntext/libs/tmr/trainbyaffixes.py
  pysyntext/libs/ud/conllu.py
  pysyntext/libs/ud/udt.py
  pysyntext/libs/ud/udtxposdata.json
  pysyntext/predefinator.py
  pysyntext/xpostrain.py
  setup.py
Labels: updating
